WARNING:root:Traceback (most recent call last):
  File "d:\Users\faris\Documents\GitHub\expanded_empires\HoI4-to-Stellaris-Converter\naive_parser.py", line 92, in ParseSaveFile
    alllines = open(path, encoding="utf-8").read()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3312.0_x64__qbz5n2kfra8p0\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9e in position 7764255: invalid start byte

INFO:root:Carrying on regardless.
